### ISSUE TITLE
Scene:enter() is called twice once in a while (rare)

### ISSUE THREAD

**Issue by Whitebrim** [NobleRobot/NobleEngine#19]
I'm having strange behaviour when it's gameover and scene transition from `game scene` to `main menu` scene, very rare MainMenu:enter() is called twice and it breaks scene initialization.
![image](https://user-images.githubusercontent.com/23287829/171972079-4d4bb76c-b3db-4126-8977-1f5278994623.png)

**Comment by paulstraw** [comment]
I'm also having this issue. After some debugging, I've found that `onMidpoint` will sometimes be called twice. The root problem is that `Sequence:updateCallbacks`' `callTimeRange` function can sometimes be called twice for a given callback, but I haven't been able to figure out quite why that is. As a quick workaround, I just added this to the top of my base scene subclass `:enter()`:

```
if self._enterComplete then
	return
end
self._enterComplete = true
```

**Comment by Mark-LaCroix** [comment]
Oh, nice catch! I'm working on overhauling the transition system right now so I'll take a look at this. This may be a bug in Sequence, or perhaps I've misused it for this use-case and need to correct it in the engine.

One thing I could do is just have an early exit from `enter` if it's called a second time on the current scene, but I'd rather fix it further up the chain if possible.
