### ISSUE TITLE
Typo in Sequence.lua file

### ISSUE THREAD

**Issue by stiv-iv** [NobleRobot/NobleEngine#49]
Typo in 432 line in libraries/Sequence.lua

local indexInRunningTable = table.indexOfElement(self)

Correct version:
local indexInRunningTable = table.indexOfElement(_runningSequences, self)

Due to a typo, the stop and pause functions did not work.

**Comment by Mark-LaCroix** [comment]
Oh, good catch!

The plan eventually is to update that library with the published one here: https://github.com/NicMagnier/PlaydateSequence, which has that fix, but in the meantime if you want to submit a pull request with that change I'd be happy to pull it (if for no other reason that to to get your name on the contributor's list).

**Comment by Mark-LaCroix** [comment]
Solved by #50
