### ISSUE TITLE
Add support for custom scene transitions

### ISSUE THREAD

**Issue by ejb** [NobleRobot/NobleEngine#51]
**Describe the feature**

I love Noble Engine's scene transitions, and it would be fantastic to be able to define custom ones.

For example: having the game's own character walk across the screen as a wipe.

**Describe alternatives you've considered**

I'm not sure how else this could be achieved in a way that doesn't feel hacky.

**Comment by GammaGames** [comment]
There's a new transition system, it's a bit more customizable 👀 I don't think the docs are completely done yet though

**Comment by Mark-LaCroix** [comment]
This was introduced in #62. Documentation is light, but you should be able to use an existing transition as a template in order to make your own.
